name       : weston
version    : 8.0.0
release    : 26
source     :
    - https://gitlab.freedesktop.org/wayland/weston/-/archive/8.0.0/weston-8.0.0.tar.gz : 4d6495057b1e31fbc8fd32f147291f0f3b49d79ff19d0b4ffafa53a49d5dbcd6
homepage   : https://gitlab.freedesktop.org/wayland/weston
license    : MIT
component  : desktop.wayland
summary    : A lightweight and functional Wayland compositor
description: |
    Weston is the reference implementation of a Wayland compositor, as well as a useful environment in and of itself. Out of the box, Weston provides a very basic desktop, or a full-featured environment for non-desktop uses such as automotive, embedded, in-flight, industrial, kiosks, set-top boxes and TVs. It also provides a library allowing other projects to build their own full-featured environments on top of Weston's core.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(freerdp2)
    - pkgconfig(gbm)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libevdev)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libva)
    - pkgconfig(libwebp)
    - pkgconfig(mtdev)
    - pkgconfig(pango)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xcursor)
    - pkgconfig(xkbcommon)
setup      : |
    %patch -p1 < $pkgfiles/pipewire-add-support-for-0.3-api.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
