name       : weston
version    : 1.7.93
release    : 7
source     :
    - http://wayland.freedesktop.org/releases/weston-1.7.93.tar.xz : d995c6967f93c7cb21f6f03a7b1cd7ffa1ce904725c6c2ae06124931784b969c
license    : MIT
summary    : Weston SDK
description: |
    Weston SDK
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(cairo-xcb)
    - pkgconfig(xcursor)
    - pkgconfig(x11)
    - pkgconfig(libdrm)
    - pkgconfig(xcb)
    - pkgconfig(libudev)
    - pkgconfig(libinput)
    - pkgconfig(wayland-client)
    - pkgconfig(pixman-1)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - pkgconfig(libva)
    - pkgconfig(pangocairo)
    - pkgconfig(glu)
    - pkgconfig(lcms2)
    - pkgconfig(mtdev)
    - pkgconfig(xkbcommon)
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-libunwind    \
                          --enable-weston-launch \
                          --enable-demo-clients
build      : |
    %make
install    : |
    %make_install
