name       : weston
version    : 1.10.0
release    : 8
source     :
    - https://wayland.freedesktop.org/releases/weston-1.10.0.tar.xz : e0b2004d00d8293ddf7903ca283c1746afa9ccb5919ab50fd04397ff472aa5c1
license    : MIT
summary    : Weston SDK
description: |
    Weston SDK
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(cairo-xcb)
    - pkgconfig(xcursor)
    - pkgconfig(x11)
    - pkgconfig(libdrm)
    - pkgconfig(xcb)
    - pkgconfig(libudev)
    - pkgconfig(libinput)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(pixman-1)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - pkgconfig(libva)
    - pkgconfig(pangocairo)
    - pkgconfig(glu)
    - pkgconfig(lcms2)
    - pkgconfig(mtdev)
    - pkgconfig(colord)
    - pkgconfig(xkbcommon)
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-libunwind    \
                          --enable-weston-launch \
                          --enable-clients \
                          --enable-simple-clients \
                          --enable-simple-egl-clients \
                          --enable-demo-clients-install
build      : |
    %make
install    : |
    %make_install
