name       : weston
version    : 5.0.0
release    : 19
source     :
    - https://wayland.freedesktop.org/releases/weston-5.0.0.tar.xz : 15a23423bcfa45e31e1dedc0cd524ba71e2930df174fde9c99b71a537c4e4caf
license    : MIT
component  : desktop.wayland
summary    : Weston SDK
description: |
    Weston SDK
builddeps  :
    - pkgconfig(cairo-xcb)
    - pkgconfig(colord)
    - pkgconfig(egl)
    - pkgconfig(glu)
    - pkgconfig(lcms2)
    - pkgconfig(libdrm)
    - pkgconfig(libinput)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(libwebp)
    - pkgconfig(mtdev)
    - pkgconfig(pangocairo)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcursor)
    - pkgconfig(xkbcommon)
setup      : |
    %configure --disable-libunwind \
        --enable-weston-launch \
        --enable-clients \
        --enable-simple-clients \
        --enable-simple-egl-clients \
        --enable-demo-clients-install
build      : |
    %make
install    : |
    %make_install
