name       : weston
version    : 1.7.0
release    : 5
source     :
    - http://wayland.freedesktop.org/releases/weston-1.7.0.tar.xz : 1c4511945f3f476c24af712e82a7b500ae91a99cbc0fe2e381da1449125166cd
license    : MIT
summary    : Weston SDK
description: |
    Weston SDK
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(cairo-xcb)
    - pkgconfig(xcursor)
    - pkgconfig(x11)
    - pkgconfig(libdrm)
    - pkgconfig(xcb)
    - pkgconfig(libudev)
    - pkgconfig(libinput)
    - pkgconfig(wayland-client)
    - pkgconfig(pixman-1)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - pkgconfig(libva)
    - pkgconfig(pangocairo)
    - pkgconfig(glu)
    - pkgconfig(lcms2)
    - pkgconfig(mtdev)
    - pkgconfig(xkbcommon)
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-libunwind    \
                          --enable-weston-launch \
                          --enable-demo-clients
build      : |
    %make
install    : |
    %make_install
