name       : weston
version    : 3.0.0
release    : 16
source     :
    - https://wayland.freedesktop.org/releases/weston-3.0.0.tar.xz : cde1d55e8dd70c3cbb3d1ec72f60e60000041579caa1d6a262bd9c35e93723a5
license    : MIT
component  : desktop.wayland
summary    : Weston SDK
description: |
    Weston SDK
builddeps  :
    - pkgconfig(cairo-xcb)
    - pkgconfig(colord)
    - pkgconfig(egl)
    - pkgconfig(glu)
    - pkgconfig(lcms2)
    - pkgconfig(libdrm)
    - pkgconfig(libinput)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(libwebp)
    - pkgconfig(mtdev)
    - pkgconfig(pangocairo)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcursor)
    - pkgconfig(xkbcommon)
setup      : |
    %configure --disable-libunwind \
        --enable-weston-launch \
        --enable-clients \
        --enable-simple-clients \
        --enable-simple-egl-clients \
        --enable-demo-clients-install
build      : |
    %make
install    : |
    %make_install
