name       : weston
version    : 8.0.0
release    : 23
source     :
    - https://gitlab.freedesktop.org/wayland/weston/-/archive/8.0.0/weston-8.0.0.tar.gz : 4d6495057b1e31fbc8fd32f147291f0f3b49d79ff19d0b4ffafa53a49d5dbcd6
license    : MIT
component  : desktop.wayland
summary    : Weston SDK
description: |
    Weston SDK
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(freerdp2)
    - pkgconfig(gbm)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libevdev)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(libwebp)
    - pkgconfig(mtdev)
    - pkgconfig(pango)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xcursor)
    - pkgconfig(xkbcommon)
setup      : |
    %patch -p1 < $pkgfiles/pipewire-add-support-for-0.3-api.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
